# Generated by Django 3.2 on 2022-08-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_block', models.CharField(max_length=100)),
                ('cost_apart', models.CharField(max_length=100)),
                ('number_kol', models.CharField(max_length=100)),
                ('floor_kol', models.CharField(max_length=100)),
                ('num_apart_per_floor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, default='--Без-хоз--', max_length=100, null=True)),
                ('data_sales', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Выкуп', 'Выкуп'), ('Выкуп не до конца', 'Выкуп не до конца'), ('Расторгнуто', 'Расторгнуто'), ('Не продано', 'Не продано')], max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('total_area', models.CharField(max_length=100)),
            ],
        ),
    ]
